### PR TITLE
Added consul as working backend, ui is enabled

### PR DESCRIPTION
**Pull request by StevenPG**
@mikepop36 

Not sure if you've messed with consul at all. Still trying to reconcile SCCS in my branch atm, I have an hour or so to bang on it today.

Tested this locally, stands up successfully.

### CODE REVIEW

**Comment by mikepop36** [comment]
I ended up opening a PR into this branch. I had to end up disabling the configuration portion of the service since I wasn't sure how to resolve an ACL issue with consul. After that, adding the consul container host as an env var to the api services, I was able to connect with the server.

**Comment by StevenPG** [comment]
@mikepop36 So on your local, inside compose api-a and api-b will hook up to the cloud server correctly? I get timeout errors constantly. Haven't gotten to see Consul/Vault yet.

**Comment by mikepop36** [comment]
@StevenPG it looks like I set the read timeout incorrectly. Opted for 10 seconds now, would you be able to verify?

**Comment by StevenPG** [comment]
I can't find any docs (on mobile) that said it's in milliseconds vs seconds.

I'll take a look tonight and see if everything loads up for me and approve.

**Pull request merged**
